### ISSUE TITLE
Error in Running Wrapper.py(data.npz is missing)

### ISSUE THREAD

**Issue by mudithnirmala** [Damowerko/opf#5]
Hi I am interested in your work in opf but when I tried to run the wrapper.py I encountered the following error.

![image](https://user-images.githubusercontent.com/52857978/106643023-2044e400-65af-11eb-929f-0e8a53b94479.png)

Then I tried to directly run data.py to generate data but it also ended up in an error. Could you please help me to run the code.

**Comment by Damowerko** [comment]
Sorry this might be a bit late. Are you still working on this?

**Comment by Damowerko** [comment]
I will add instructions on how to run code.

**Comment by mudithnirmala** [comment]
Thank You! that will be helpful :-)

**Comment by Damowerko** [comment]
I am closing this since instructions were added 2y ago.
